
subdir-ccflags-y += -DUSE_GPIO \
-I$(srctree)/drivers/spi/mediatek/$(MTK_PLATFORM)

subdir-ccflags-y += -DMICROPANEL_BPP=1

obj-y	+= OledMono.o
obj-y	+= OledDriver_intf.o
obj-y	+= OledDriver_2832TSWUG01.o


